[package]
name = "laq-fort"
version = "0.0.1"
edition = "2021"

[dependencies]
pqc_kyber = "0.7.1"
rand = "0.8.4"
aes-gcm = "0.11.0-pre.1"
clap = { version = "4.5.18", features = ["derive"] }
zeroize = "1.4"
base64 = "0.13.0"
